name: Deploy

on: 
  push:
    branches:
      - main # 监听main分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: 123.249.31.52
        user: 'root'
        port: 22
        password: ${{ secrets.REMOTE_PWD }}
        script: |
          cd /root/app/github-actions
          ./website.sh
